### ISSUE TITLE
Remove week3-AppDev-crud/crud-java/target

### ISSUE THREAD

**Issue by tringuyen-yw** [DataStax-Academy/cassandra-workshop-series#14]
Not sure if the java [week3-AppDev-crud/crud-java/target](https://github.com/DataStax-Academy/cassandra-workshop-series/tree/master/week3-AppDev-crud/crud-java/target) content has been intentionally committed to the repo. If not could this be removed?

**Comment by clun** [comment]
You are correct those have been updated before the `.gitIgnore` has been correctly setup.

**Comment by clun** [comment]
Updated are done in PR #19
